[package]
name = "egui_test"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-queue = "0.3.12"
eframe = "0.31.1"
egui = "0.31.1"
egui_plot = "0.32.1"
env_logger = "0.11"
serde = "1.0.219"
serde_json = "1.0.140"
